export const HANDLE_GEO_AUTO_COMPLETE_REQUEST = "HANDLE_GEO_AUTO_COMPLETE_REQUEST";
export const HANDLE_LIST_PROPERTIES_REQUEST = "HANDLE_LIST_PROPERTIES_REQUEST";
export const LIST_PROPERTIES_REQUEST_COMPLETE = "LIST_PROPERTIES_REQUEST_COMPLETE";
export const UPDATE_PROPERTIES_TABLE = "UPDATE_PROPERTIES_TABLE";
export const ON_FILTER_FORM_FIELDS_CHANGE = "ON_FILTER_FORM_FIELDS_CHANGE";
export const FILTER_FORM_FIELDS_ERROR = "FILTER_FORM_FIELDS_ERROR";