export const HANDLE_GEO_AUTO_COMPLETE_REQUEST = "HANDLE_GEO_AUTO_COMPLETE_REQUEST";
export const HANDLE_LIST_PROPERTIES_REQUEST = "HANDLE_LIST_PROPERTIES_REQUEST";
export const ON_FILTER_FORM_FIELDS_CHANGE = "ON_FILTER_FORM_FIELDS_CHANGE";